export const types = {
    CHANGE_TITLE : 'CHANGE_TITLE',
    WITH_PARAMS :  "WITH_PARAMS",
    INPUT_VALUE : 'INPUT_VALUE',
    ADD_USER: 'ADD_USER',
    DELETE_USER: "DELETE_USER",
    CALCULATOR_ADD: 'CALCULATOR_ADD',
    CALCULATOR_SUBTRACT: 'CALCULATOR_SUBTRACT',
    CALCULATOR_MULTIPLY: 'CALCULATOR_MULTIPLY',
    CALCULATOR_DIVIDE: 'CALCULATOR_DIVIDE',
    CALCULATOR_CLEAR: 'CALCULATOR_CLEAR'
}